name: ci

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:v0.11.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Write Dockerfile
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
          echo "RUN dd if=/dev/zero of=layer bs=1024KB count=500" >> Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          outputs: type=registry,dest=ghcr.io/${{ github.repository_owner }}/test:5g,push=true,compression=uncompressed
          tags: ghcr.io/${{ github.repository_owner }}/test:${{ matrix.id }}